### ISSUE TITLE
Server Crash (Ticking Entity)

### ISSUE THREAD

**Issue by Lukebb04** [QuantumXenon/origins-randomiser#1]
The server crashes with the following mods

- origins-randomiser-1.4.jar
- origins-plus-plus-1.7.jar
- Origins-1.19-1.6.2.jar
- Pehkui-3.4.1+1.14.4-1.19.2.jar
- fabric-api-0.60.0+1.19.2.jar

```
---- Minecraft Crash Report ----

Description: Ticking entity

java.lang.NoSuchMethodError: 'int net.minecraft.class_2170.method_9249(net.minecraft.class_2168, java.lang.String)'
	at io.github.apace100.apoli.power.factory.action.EntityActions.lambda$register$15(EntityActions.java:235)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.factory.action.meta.AndAction.lambda$action$0(AndAction.java:14)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.github.apace100.apoli.power.factory.action.meta.AndAction.action(AndAction.java:14)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.ActionOverTimePower.tick(ActionOverTimePower.java:46)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.github.apace100.apoli.component.PowerHolderComponentImpl.serverTick(PowerHolderComponentImpl.java:172)
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_1657_13562080.tickServerComponents(Unknown Source)
	at net.minecraft.class_3218.handler$zch000$tick(class_3218.java:2226)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at io.github.apace100.apoli.power.factory.action.EntityActions.lambda$register$15(EntityActions.java:235)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.factory.action.meta.AndAction.lambda$action$0(AndAction.java:14)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.github.apace100.apoli.power.factory.action.meta.AndAction.action(AndAction.java:14)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.ActionOverTimePower.tick(ActionOverTimePower.java:46)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.github.apace100.apoli.component.PowerHolderComponentImpl.serverTick(PowerHolderComponentImpl.java:172)
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_1657_13562080.tickServerComponents(Unknown Source)
	at net.minecraft.class_3218.handler$zch000$tick(class_3218.java:2226)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)

-- Entity being ticked --
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by QuantumXenon** [comment]
Origins (Fabric) doesn't seem to work properly with addons or datapacks in 1.19.1 or 1.19.2. Try downgrading to 1.19 for now until the Origins mod is updated.

(See here: https://github.com/apace100/origins-fabric/issues/581)
