### ISSUE TITLE
Forge version is incompatible with Create on server

### ISSUE THREAD

**Issue by Hypario** [QuantumXenon/origins-randomiser#7]
Hello ! when trying to install the mod with Create installed on the same server. I get a config error, I don't know if it comes from Create or this mod.

Here is the crash report I get

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-09-04 07:22:32
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
  at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.2.21-universal.jar%23326!/:?] {re:classloading}
  at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.19.2-43.2.21-universal.jar%23326!/:?] {re:classloading}
  at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23321!/:?] {re:classloading,re:mixin,pl:mixin:A}
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
  at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
  at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.2.21.jar%2367!/:?] {}
  at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
  at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
  at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
  at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
  at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
  at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
  at me.shedaniel.autoconfig.AutoConfig.getConfigHolder(AutoConfig.java:77) ~[cloth-config-8.3.103-forge.jar%23228!/:?] {re:classloading,pl:runtimedistcleaner:A}
-- MOD create --
Details:
  Caused by 0: java.lang.ExceptionInInitializerError
    at java.lang.Class.forName0(Native Method) ~[?:?] {re:mixin}
    at java.lang.Class.forName(Unknown Source) ~[?:?] {re:mixin}
    at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19.2-43.2.21.jar%23323!/:?] {}
    at java.util.ArrayList.forEach(Unknown Source) ~[?:?] {re:mixin}
    at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19.2-43.2.21.jar%23323!/:?] {}
    at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19.2-43.2.21.jar%23323!/:?] {}
    at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.21.jar%23322!/:?] {}
    at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
    at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
    at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
    at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
    at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
    at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

  Mod File: /data/mods/create-1.19.2-0.5.1.c.jar
  Failure message: Create (create) has failed to load correctly
    java.lang.ExceptionInInitializerError: null
  Mod Version: 0.5.1.c
  Mod Issue URL: https://github.com/Creators-of-Create/Create/issues
  Exception message: java.lang.RuntimeException: Config 'class quantumxenon.origins_randomiser.config.OriginsRandomiserConfig' has not been registered
Stacktrace:
  at me.shedaniel.autoconfig.AutoConfig.getConfigHolder(AutoConfig.java:77) ~[cloth-config-8.3.103-forge.jar%23228!/:?] {re:classloading,pl:runtimedistcleaner:A}
  at quantumxenon.origins_randomiser.config.OriginsRandomiserConfig.getConfig(OriginsRandomiserConfig.java:20) ~[origins-randomiser-2.3+forge.jar%23291!/:?] {re:mixin,re:classloading}
  at net.minecraft.server.level.ServerPlayer.<clinit>(ServerPlayer.java:148) ~[server-1.19.2-20220805.130853-srg.jar%23321!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:netherportalfix.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ForgeServerPlayerMixin,pl:mixin:APP:forgivingvoid.mixins.json:ServerPlayerAccessor,pl:mixin:APP:pehkui.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:origins_randomiser.mixins.json:ServerPlayerMixin,pl:mixin:APP:byg.mixins.json:common.entity.MixinServerPlayer,pl:mixin:APP:vanishmod.mixins.json:ServerPlayerMixin,pl:mixin:APP:securitycraft.mixins.json:camera.ServerPlayerMixin,pl:mixin:A}
  at java.lang.Class.forName0(Native Method) ~[?:?] {re:mixin}
  at java.lang.Class.forName(Unknown Source) ~[?:?] {re:mixin}
  at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19.2-43.2.21.jar%23323!/:?] {}
  at java.util.ArrayList.forEach(Unknown Source) ~[?:?] {re:mixin}
  at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19.2-43.2.21.jar%23323!/:?] {}
  at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19.2-43.2.21.jar%23323!/:?] {}
  at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.21.jar%23322!/:?] {}
  at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
  at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
  at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
  at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
  at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
  at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
  at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}


-- System Details --
Details:
  Minecraft Version: 1.19.2
  Minecraft Version ID: 1.19.2
  Operating System: Linux (amd64) version 5.15.0-78-generic
  Java Version: 17.0.8, Eclipse Adoptium
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
  Memory: 16329583424 bytes (15573 MiB) / 17179869184 bytes (16384 MiB) up to 25769803776 bytes (24576 MiB)
  CPUs: 8
  Processor Vendor: GenuineIntel
  Processor Name: Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz
  Identifier: Intel64 Family 6 Model 94 Stepping 3
  Microarchitecture: Skylake (Client)
  Frequency (GHz): 3.50
  Number of physical packages: 1
  Number of physical CPUs: 4
  Number of logical CPUs: 8
  Graphics card #0 name: unknown
  Graphics card #0 vendor: unknown
  Graphics card #0 VRAM (MB): 0.00
  Graphics card #0 deviceId: unknown
  Graphics card #0 versionInfo: unknown
  Virtual memory max (MB): 16892.31
  Virtual memory used (MB): 3306.41
  Swap memory total (MB): 1023.99
  Swap memory used (MB): 1.01
  JVM Flags: 2 total; -Xmx24G -Xms16G
  ModLauncher: 10.0.8+10.0.8+main.0ef7e830
  ModLauncher launch target: forgeserver
  ModLauncher naming: srg
  ModLauncher services:
    mixin-0.8.5.jar mixin PLUGINSERVICE
    eventbus-6.0.3.jar eventbus PLUGINSERVICE
    fmlloader-1.19.2-43.2.21.jar slf4jfixer PLUGINSERVICE
    fmlloader-1.19.2-43.2.21.jar object_holder_definalize PLUGINSERVICE
    fmlloader-1.19.2-43.2.21.jar runtime_enum_extender PLUGINSERVICE
    fmlloader-1.19.2-43.2.21.jar capability_token_subclass PLUGINSERVICE
    accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE
    fmlloader-1.19.2-43.2.21.jar runtimedistcleaner PLUGINSERVICE
    modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE
    modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE
  FML Language Providers:
    minecraft@1.0
    javafml@null
    kotlinforforge@3.12.0
    lowcodefml@null
  Mod List:
    supermartijn642configlib-1.1.7-forge-mc1.19.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.7               |COMMON_SET|Manifest: NOSIGNATURE
    netherportalfix-forge-1.19-10.0.1.jar             |NetherPortalFix               |netherportalfix               |10.0.1              |COMMON_SET|Manifest: NOSIGNATURE
    additionalentityattributes-forge-1.19-1.0.1+1.19.j|Additional Entity Attributes  |additionalentityattributes    |1.0.1+1.19          |COMMON_SET|Manifest: NOSIGNATURE
    scena-forge-1.0.95.jar                            |Scena                         |scena                         |1.0.95              |COMMON_SET|Manifest: NOSIGNATURE
    player-animation-lib-forge-1.0.2.jar              |Player Animator               |playeranimator                |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
    connectivity-1.19.2-4.5.jar                       |Connectivity Mod              |connectivity                  |1.19.2-4.5          |COMMON_SET|Manifest: NOSIGNATURE
    apoli-forge-1.19.2-2.6.1.2.jar                    |Apoli                         |apoli                         |1.19.2-2.6.1.2      |COMMON_SET|Manifest: NOSIGNATURE
    sophisticatedcore-1.19.2-0.5.83.394.jar           |Sophisticated Core            |sophisticatedcore             |1.19.2-0.5.83.394   |COMMON_SET|Manifest: NOSIGNATURE
    rubidium-0.6.2b.jar                               |Rubidium                      |rubidium                      |0.6.2b              |COMMON_SET|Manifest: NOSIGNATURE
    CTM-1.19.2-1.1.6+8.jar                            |ConnectedTexturesMod          |ctm                           |1.19.2-1.1.6+8      |COMMON_SET|Manifest: NOSIGNATURE
    Controlling-forge-1.19.2-10.0+7.jar               |Controlling                   |controlling                   |10.0+7              |COMMON_SET|Manifest: NOSIGNATURE
    modernlife-1.19.2-1.59.jar                        |Modern Life                   |modernlife                    |1.19.2-1.59         |COMMON_SET|Manifest: NOSIGNATURE
    citadel-2.1.4-1.19.jar                            |Citadel                       |citadel                       |2.1.4               |COMMON_SET|Manifest: NOSIGNATURE
    alexsmobs-1.21.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.21.1              |COMMON_SET|Manifest: NOSIGNATURE
    Bookshelf-Forge-1.19.2-16.3.20.jar                |Bookshelf                     |bookshelf                     |16.3.20             |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
    sophisticatedbackpacks-1.19.2-3.18.55.889.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.19.2-3.18.55.889  |COMMON_SET|Manifest: NOSIGNATURE
    forgivingvoid-forge-1.19-7.0.0.jar                |Forgiving Void                |forgivingvoid                 |7.0.0               |COMMON_SET|Manifest: NOSIGNATURE
    mcw-doors-1.1.0forge-mc1.19.2.jar                 |Macaw's Doors                 |mcwdoors                      |1.1.0               |COMMON_SET|Manifest: NOSIGNATURE
    fakename-1.19.2-1.3.1.jar                         |Fakename                      |fakename                      |1.3.1               |COMMON_SET|Manifest: NOSIGNATURE
    balm-forge-1.19.2-4.5.7.jar                       |Balm                          |balm                          |4.5.7               |COMMON_SET|Manifest: NOSIGNATURE
    JustEnoughResources-1.19.2-1.2.2.236.jar          |Just Enough Resources         |jeresources                   |1.2.2.236           |COMMON_SET|Manifest: NOSIGNATURE
    cloth-config-8.3.103-forge.jar                    |Cloth Config v8 API           |cloth_config                  |8.3.103             |COMMON_SET|Manifest: NOSIGNATURE
    supplementaries-1.19.2-2.3.22.jar                 |Supplementaries               |supplementaries               |1.19.2-2.3.22       |COMMON_SET|Manifest: NOSIGNATURE
    konkrete_forge_1.6.1_MC_1.19-1.19.2.jar           |Konkrete                      |konkrete                      |1.6.1               |COMMON_SET|Manifest: NOSIGNATURE
    corpse-1.19.2-1.0.0.jar                           |Corpse                        |corpse                        |1.19.2-1.0.0        |COMMON_SET|Manifest: NOSIGNATURE
    chipped-forge-1.19.2-2.1.5.jar                    |Chipped                       |chipped                       |2.1.5               |COMMON_SET|Manifest: NOSIGNATURE
    FarmersDelight-1.19.2-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.19.2-1.2.3        |COMMON_SET|Manifest: NOSIGNATURE
    CroptopiaAdditions-1.19.2-FORGE-2.0.FINAL.jar     |Croptopia Additions           |croptopia_additions           |2.0.0.              |COMMON_SET|Manifest: NOSIGNATURE
    signpost-1.19.2-2.01.0.jar                        |Signpost                      |signpost                      |1.19.2-2.01.0       |COMMON_SET|Manifest: NOSIGNATURE
    stacking_potions-1.19.2-2.0.jar                   |Stacking Potions              |stacking_potions              |2.0                 |COMMON_SET|Manifest: NOSIGNATURE
    mcw-fences-1.0.7-mc1.19.2forge.jar                |Macaw's Fences and Walls      |mcwfences                     |1.0.7               |COMMON_SET|Manifest: NOSIGNATURE
    supermartijn642corelib-1.1.12-forge-mc1.19.2.jar  |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.12              |COMMON_SET|Manifest: NOSIGNATURE
    simplylight-1.19.2-1.4.5-build.42.jar             |Simply Light                  |simplylight                   |1.19.2-1.4.5-build.4|COMMON_SET|Manifest: NOSIGNATURE
    DimensionAccessManager-1.19.2-3.1.0.jar           |Dimension Access Manager      |dimension_access_manager      |3.1.0               |COMMON_SET|Manifest: NOSIGNATURE
    curios-forge-1.19.2-5.1.4.1.jar                   |Curios API                    |curios                        |1.19.2-5.1.4.1      |COMMON_SET|Manifest: NOSIGNATURE
    origins-forge-1.19.2-1.7.1.2-all.jar              |Origins                       |origins                       |1.19.2-1.7.1.2      |COMMON_SET|Manifest: NOSIGNATURE
    Extra-Keybinds.1.19-1.1.jar                       |Extra Keybinds                |extra_keybinds                |1.1                 |COMMON_SET|Manifest: NOSIGNATURE
    camera-1.19.2-1.0.4.jar                           |Camera Mod                    |camera                        |1.19.2-1.0.4        |COMMON_SET|Manifest: NOSIGNATURE
    bettervillage-forge-1.19.2-3.2.0.jar              |Better village                |bettervillage                 |3.1.0               |COMMON_SET|Manifest: NOSIGNATURE
    elevatorid-1.19.2-1.8.9.jar                       |Elevator Mod                  |elevatorid                    |1.19.2-1.8.9        |COMMON_SET|Manifest: NOSIGNATURE
    Runelic-Forge-1.19.2-14.1.4.jar                   |Runelic                       |runelic                       |14.1.4              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f
:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
    resourcefullib-forge-1.19.2-1.1.24.jar            |Resourceful Lib               |resourcefullib                |1.1.24              |COMMON_SET|Manifest: NOSIGNATURE
    worldedit-mod-7.2.12.jar                          |WorldEdit                     |worldedit                     |7.2.12+6240-87f4ae1 |COMMON_SET|Manifest: NOSIGNATURE
    architectury-6.5.85-forge.jar                     |Architectury                  |architectury                  |6.5.85              |COMMON_SET|Manifest: NOSIGNATURE
    mcw-furniture-3.1.0-mc1.19.2forge.jar             |Macaw's Furniture             |mcwfurnitures                 |3.1.0               |COMMON_SET|Manifest: NOSIGNATURE
    cupboard-1.19.2-1.7.jar                           |Cupboard utilities            |cupboard                      |1.19.2-1.7          |COMMON_SET|Manifest: NOSIGNATURE
    Adorn-3.9.1+1.19.2-forge.jar                      |Adorn                         |adorn                         |3.9.1+1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
    SizeShiftingPotions-forge-1.19.2-1.5.1.jar        |Size Shifting Potions         |sizeshiftingpotions           |1.5.1               |COMMON_SET|Manifest: NOSIGNATURE
    FastLeafDecay-30.jar                              |FastLeafDecay                 |fastleafdecay                 |30                  |COMMON_SET|Manifest: NOSIGNATURE
    waterframes-1.19.2-1.4.1a.jar                     |WaterFrames                   |waterframes                   |1.4.1a              |COMMON_SET|Manifest: NOSIGNATURE
    mcw-lights-1.0.6-mc1.19.2forge.jar                |Macaw's Lights and Lamps      |mcwlights                     |1.0.6               |COMMON_SET|Manifest: NOSIGNATURE
    frozen_delight_1.3.2_forge_1.19.2.jar             |Frozen Delight (by NoCube)    |frozen_delight                |1.3.2               |COMMON_SET|Manifest: NOSIGNATURE
    elytraslot-forge-6.1.1+1.19.2.jar                 |Elytra Slot                   |elytraslot                    |6.1.1+1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
    inventorysorter-1.19.2-21.0.4.jar                 |Simple Inventory Sorter       |inventorysorter               |21.0.4              |COMMON_SET|Manifest: NOSIGNATURE
    trashslot-forge-1.19-12.0.2.jar                   |TrashSlot                     |trashslot                     |12.0.2              |COMMON_SET|Manifest: NOSIGNATURE
    xlpackets-1.18.2-2.1.jar                          |XL Packets                    |xlpackets                     |1.18.2-2.1          |COMMON_SET|Manifest: NOSIGNATURE
    jei-1.19.2-forge-11.6.0.1017.jar                  |Just Enough Items             |jei                           |11.6.0.1017         |COMMON_SET|Manifest: NOSIGNATURE
    Pehkui-3.7.8+1.19.2-forge.jar                     |Pehkui                        |pehkui                        |3.7.8+1.19.2-forge  |COMMON_SET|Manifest: NOSIGNATURE
    Extra potions 0.2.3.jar                           |Extra potions                 |extra_potions                 |0.2.3               |COMMON_SET|Manifest: NOSIGNATURE
    libraryferret-forge-1.19.2-4.0.0.jar              |Library ferret                |libraryferret                 |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
    caelus-forge-1.19.2-3.0.0.6.jar                   |Caelus API                    |caelus                        |1.19.2-3.0.0.6      |COMMON_SET|Manifest: NOSIGNATURE
    waystones-forge-1.19.2-11.4.1.jar                 |Waystones                     |waystones                     |11.4.1              |COMMON_SET|Manifest: NOSIGNATURE
    Clumps-forge-1.19.2-9.0.0+14.jar                  |Clumps                        |clumps                        |9.0.0+14            |COMMON_SET|Manifest: NOSIGNATURE
    journeymap-1.19.2-5.9.7-forge.jar                 |Journeymap                    |journeymap                    |5.9.7               |COMMON_SET|Manifest: NOSIGNATURE
    untamedwilds-1.19.2-3.0.2.jar                     |Untamed Wilds                 |untamedwilds                  |3.0.2               |COMMON_SET|Manifest: NOSIGNATURE
    configured-2.1.1-1.19.2.jar                       |Configured                    |configured                    |2.1.1               |COMMON_SET|Manifest: NOSIGNATURE
    CustomPlayerModels-1.19-0.6.10a.jar               |Customizable Player Models    |cpm                           |0.6.10a             |COMMON_SET|Manifest: NOSIGNATURE
    codAaoxh-1.0.0-forge.jar                          |MidnightLib                   |midnightlib                   |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
    JeiTweaker-forge-1.19.2-4.0.12.jar                |JeiTweaker                    |jeitweaker                    |4.0.12              |COMMON_SET|Manifest: NOSIGNATURE
    CraftTweaker-forge-1.19.2-10.1.49.jar             |CraftTweaker                  |crafttweaker                  |10.1.49             |COMMON_SET|Manifest: NOSIGNATURE
    frozenup-1.19.2-2.1.2-forge.jar                   |Frozen Up                     |frozenup                      |2.1.2-forge         |COMMON_SET|Manifest: NOSIGNATURE
    forge-1.19.2-43.2.21-universal.jar                |Forge                         |forge                         |43.2.21             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
    inzheFoPCore-v.4.0.0-1.19.2.jar                   |inzhefop core                 |inzhefopcore                  |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
    mcw-paths-1.0.3forge-mc1.19.2.jar                 |Macaw's Paths and Pavings     |mcwpaths                      |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
    emotecraft-for-MC1.19.2-2.2.5-forge.jar           |Emotecraft                    |emotecraft                    |2.2.5               |COMMON_SET|Manifest: NOSIGNATURE
    alcocraftplus-1.19.2-forge-1.0.1.jar              |Alcocraft                     |alcocraftplus                 |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
    DungeonsArise-1.19.2-2.1.54-release.jar           |When Dungeons Arise           |dungeons_arise                |2.1.54-1.19.2       |COMMON_SET|Manifest: NOSIGNATURE
    server-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |COMMON_SET|Manifest: NOSIGNATURE
    voicechat-forge-1.19.2-2.4.21.jar                 |Simple Voice Chat             |voicechat                     |1.19.2-2.4.21       |COMMON_SET|Manifest: NOSIGNATURE
    TerraBlender-forge-1.19.2-2.0.1.136.jar           |TerraBlender                  |terrablender                  |2.0.1.136           |COMMON_SET|Manifest: NOSIGNATURE
    moonlight-1.19.2-2.2.44-forge.jar                 |Moonlight Library             |moonlight                     |1.19.2-2.2.44       |COMMON_SET|Manifest: NOSIGNATURE
    MouseTweaks-forge-mc1.19-2.23.jar                 |Mouse Tweaks                  |mousetweaks                   |2.23                |COMMON_SET|Manifest: NOSIGNATURE
    bakingmod-forge-1.19.2-v1.0.6.jar                 |Baking Mod                    |bakingmod                     |1.0.6               |COMMON_SET|Manifest: NOSIGNATURE
    Jade-1.19.1-forge-8.8.1.jar                       |Jade                          |jade                          |8.8.1               |COMMON_SET|Manifest: NOSIGNATURE
    another_furniture-forge-1.19.2-2.1.4.jar          |Another Furniture             |another_furniture             |1.19.2-2.1.4        |COMMON_SET|Manifest: NOSIGNATURE
    CreativeCore_FORGE_v2.9.4_mc1.19.2.jar            |CreativeCore                  |creativecore                  |2.9.3               |COMMON_SET|Manifest: NOSIGNATURE
    spectrelib-forge-0.12.5+1.19.2.jar                |SpectreLib                    |spectrelib                    |0.12.5+1.19.2       |COMMON_SET|Manifest: NOSIGNATURE
    weaponmaster-multi-forge-1.19.x-3.0.3.jar         |YDM's Weapon Master           |weaponmaster                  |3.0.3               |COMMON_SET|Manifest: NOSIGNATURE
    NethersDelight-1.19-3.0.jar                       |Nether's Delight              |nethersdelight                |1.19-3.0            |COMMON_SET|Manifest: NOSIGNATURE
    cookietology-1.1.1.jar                            |Cookietology                  |cookietology                  |1.1.1               |COMMON_SET|Manifest: NOSIGNATURE
    calio-forge-1.19.2-1.7.0.1.jar                    |Calio                         |calio                         |1.19.2-1.7.0.1      |COMMON_SET|Manifest: NOSIGNATURE
    kffmod-3.12.0.jar                                 |Kotlin For Forge              |kotlinforforge                |3.12.0              |COMMON_SET|Manifest: NOSIGNATURE
    origins-plus-plus-2.1.1-forge.jar                 |Origins++                     |origins_plus_plus             |2.1.1-forge         |COMMON_SET|Manifest: NOSIGNATURE
    plushies-1.2-1.19.2.jar                           |Plushie Mod                   |plushies                      |1.2                 |COMMON_SET|Manifest: NOSIGNATURE
    FarmersRespite-1.19-2.0.jar                       |Farmer's Respite              |farmersrespite                |1.19-2.0            |COMMON_SET|Manifest: NOSIGNATURE
    flywheel-forge-1.19.2-0.6.9-18.jar                |Flywheel                      |flywheel                      |0.6.9-18            |COMMON_SET|Manifest: NOSIGNATURE
    create-1.19.2-0.5.1.c.jar                         |Create                        |create                        |0.5.1.c             |ERROR     |Manifest: NOSIGNATURE
    createdeco-1.3.3-1.19.2.jar                       |Create Deco                   |createdeco                    |1.3.3-1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
    Croptopia-1.19.2-FORGE-2.2.2.jar                  |Croptopia                     |croptopia                     |2.2.2               |COMMON_SET|Manifest: NOSIGNATURE
    PigPen-Forge-1.19.2-11.1.2.jar                    |PigPen                        |pigpen                        |11.1.2              |COMMON_SET|Manifest: NOSIGNATURE
    polymorph-forge-0.46.4+1.19.2.jar                 |Polymorph                     |polymorph                     |0.46.4+1.19.2       |COMMON_SET|Manifest: NOSIGNATURE
    [1.19.2] SecurityCraft v1.9.6.1.jar               |SecurityCraft                 |securitycraft                 |1.9.6.1             |COMMON_SET|Manifest: NOSIGNATURE
    StorageDrawers-1.19-11.1.2.jar                    |Storage Drawers               |storagedrawers                |11.1.2              |COMMON_SET|Manifest: NOSIGNATURE
    ChannelingStone_1.0.1_1.19.2.jar                  |Advanced XP                   |advanced_xp                   |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
    appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        |COMMON_SET|Manifest: NOSIGNATURE
    alexsdelight-1.4.1.jar                            |Alex's Delight                |alexsdelight                  |1.4.1               |COMMON_SET|Manifest: NOSIGNATURE
    origins-randomiser-2.3+forge.jar                  |Origins Randomiser            |origins_randomiser            |2.3+forge           |COMMON_SET|Manifest: NOSIGNATURE
    lootr-1.19-0.4.24.64.jar                          |Lootr                         |lootr                         |0.4.24.63           |COMMON_SET|Manifest: NOSIGNATURE
    connectedglass-1.1.7-forge-mc1.19.jar             |Connected Glass               |connectedglass                |1.1.7               |COMMON_SET|Manifest: NOSIGNATURE
    ItalianDelight-1.19.2 1.5-MAR_FIX.jar             |Italian Delight               |italian_delight               |1.2                 |COMMON_SET|Manifest: NOSIGNATURE
    Oh_The_Biomes_You_ll_Go-forge-1.19.2-2.0.1.4.jar  |Oh The Biomes You'll Go       |byg                           |2.0.1.4             |COMMON_SET|Manifest: NOSIGNATURE
    geckolib-forge-1.19-3.1.40.jar                    |GeckoLib                      |geckolib3                     |3.1.40              |COMMON_SET|Manifest: NOSIGNATURE
    CorgiLib-forge-1.19.2-1.0.0.34.jar                |CorgiLib                      |corgilib                      |1.0.0.34            |COMMON_SET|Manifest: NOSIGNATURE
    justzoom_forge_1.0.1-1_MC_1.19.jar                |Just Zoom                     |justzoom                      |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
    CosmeticArmorReworked-1.19.2-v1a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.19.2-v1a          |COMMON_SET|Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
    chisels-and-bits-forge-1.3.135.jar                |chisels-and-bits              |chiselsandbits                |1.3.135             |COMMON_SET|Manifest: NOSIGNATURE
    Vanishmod-1.19.2-1.1.12.jar                       |Vanishmod                     |vmod                          |1.1.12              |COMMON_SET|Manifest: NOSIGNATURE
    createaddition-1.19.2-1.0.0.jar                   |Create Crafts & Additions     |createaddition                |1.19.2-1.0.0        |COMMON_SET|Manifest: NOSIGNATURE
  Crash Report UUID: 67fd4b55-c534-4bab-955f-5e0ba813b78a
  FML: 43.2
  Forge: net.minecraftforge:43.2.21
```

**Comment by QuantumXenon** [comment]
I have been able to replicate this issue, though I do not know why this is happening. I will look into it more to see if I can figure out what is happening

**Comment by Hypario** [comment]
For the time being, I have re-made the mod myself, I'm guessing it is because of the way autoconfig works, but as I never used it, I can't be sure. 

I re-made the mod myself (using your source) for a personal project (not available on my github, as I made it private), hope you don't mind. I'll switch back to yours if the issue is fixed ;)
